#!/bin/bash

pushd /tmp

  export EDITOR=vi

  yaourt --version 2> /dev/null
  if [ $? != 0 ]
  then
    curl https://raw.github.com/nandub/archlinux/master/yaourt/yaourt-bin | bash
    yaourt -S cjdns-git
  else
    yaourt -S cjdns-git
  fi 

popd

